### PR TITLE
Possible performance improvement.

### PR DESCRIPTION
**Pull request by chriseidhof**

### CODE REVIEW

**Comment by chriseidhof** [comment]
After thinking about it, I think one possible source of performance problems is that on line 132 here the variable `d1` is fully evaluated. In the corresponding Haskell code, it's lazy. The `fits` method doesn't need the full evaluation: it only checks if the current line fits.

This pull-request makes the continuation of the line lazy, and it seems (in my very limited testing) that performance drastically improves. I'm not sure what `z` does in `best`, and I'm not sure if it's a good idea that it's now `@escaping`. 

Are there any larger test suites? Maybe @mbrandonw has some tests?

https://github.com/bkase/DoctorPretty/blob/master/Sources/DoctorPretty/RenderPretty.swift#L132

**Comment by chriseidhof** [comment]
A quick performance indication:

previously, this test took 1.9sec:

```swift
    func testSlow() {
        measure {
            let doc = (1...5).map { _ in
                (1...20).map { _ in "foo" }.map(Doc.text).fillSep()
                }.vcat()
            _ = doc.renderPrettyDefault()
        }
    }
```

After my change, it takes 0.00019 seconds (factor 10,000).

🤷‍♀️

**Comment by mbrandonw** [comment]
I've updated [pointfreeco/swift-web](https://github.com/pointfreeco/swift-web/) to use this and it does seem to speed things up a lot!

https://github.com/pointfreeco/swift-web/compare/dr-pretty-update?expand=1

**Review by bkase — APPROVED** [review]
Just tested and reproduced locally. This is so simple! I did crazy CPS and defunctionalization transforms to try to make this faster and that didn't even speed it up. Nice job!

**Comment by chenglou** [comment]
Randomly coming across this repo. Here's an add-on paper that formalizes the strictness of such pretty printer and its performance gain: https://pdfs.semanticscholar.org/c73c/a9cc74351fe7f8f3dddc69d2e82326af82c0.pdf

Basically, for strict languages, use a simple intermediate data structure.

**Comment by bkase** [comment]
@chenglou thanks! I wish I saw this earlier:

> An implementation of Wadler’s pretty printer in a strict language must avoid a literal trans- lation of the original implementation because of its exponential complexity

^^ I guess that’s what happened

**Comment by chriseidhof** [comment]
@chenglou very interesting! I think my solution is a bit different from that paper, but it feels like the paper describes a nicer (easier to understand) solution.

**Pull request merged**
